name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]   # daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_achievements: yes
